output:
  bundleOut: ../../swap/output/

schedule:
  everyMinutes: 30

sources:
  - id: baidu
    enabled: true
    # timeoutMs: 6000
    # headers:
    #   x-client: local-dev
  - id: shaoshupai
    enabled: true
  - id: weibo
    enabled: true
  - id: zhihu
    enabled: true
  - id: 36kr
    enabled: true
  - id: 52pojie
    enabled: true
  - id: bilibili
    enabled: true
  - id: douban
    enabled: true
  - id: hupu
    enabled: true
  - id: tieba
    enabled: true
  - id: juejin
    enabled: true
  - id: douyin
    enabled: true
  - id: v2ex
    enabled: true
  - id: jinritoutiao
    enabled: true
  - id: tenxunwang
    enabled: true
  - id: stackoverflow
    enabled: true
  - id: github
    enabled: true
  - id: hackernews
    enabled: true
  - id: sina_finance
    enabled: true
  - id: eastmoney
    enabled: true
  - id: xueqiu
    enabled: true
  - id: cls
    enabled: true
